### ISSUE TITLE
Switcher component

### ISSUE THREAD

**Issue by Marco-Pellegrino** [diego-apellaniz/Karamba3DUIWidgets#1]
Hi @diego-apellaniz 
The switcher component has some issue when try to use in in Grasshopper.
It does not show up correctly in the canvas.
Do you have the same issue?

![image](https://user-images.githubusercontent.com/53620289/182575140-2e647c84-b79e-4ab2-b71f-2d44839d2fd7.png)

![image](https://user-images.githubusercontent.com/53620289/182575215-873efe78-1c0e-4778-b62e-942b1e2409eb.png)

**Comment by diego-apellaniz** [comment]
Hello @Marco-Pellegrino ,

that's probably because you compiled a plugin with the Rhino7 dll reference files that you're loading in Rhino6 or viceversa. You have to compile two different gha files for both Rhino6 and Rhino7 if you want to use the widgets.

BR Diego

**Comment by Marco-Pellegrino** [comment]
Thanks @diego-apellaniz !
It finally work :)

I'll try to change some of the colors to diversify it from Karamba. Let's see how it goes :)
